services:
  mysql:
    image: mysql:8
    container_name: time-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: time_management_db
      MYSQL_USER: MYSQL_admin
      MYSQL_PASSWORD: MYSQL_admin_password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
